/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*        Automatically Generated by GLSL ShaderGen     *
*          https://github.com/mojocorp/ShaderGen       *
*******************************************************/
uniform sampler2D texUnit0;

void main (void) 
{
    vec4 color;

    color = gl_Color;

    vec4 texture0Arg0 = texture2D(texUnit0, gl_TexCoord[0].xy);
    vec4 texUnit0Arg0 = texture0Arg0;
    vec4 texUnit0Arg1 = color;
    color = clamp(texUnit0Arg0 * texUnit0Arg1, 0.0, 1.0);
    gl_FragColor = color;
}
