# SPDX-License-Identifier: GPL-3.0-or-later
name: Build
on:
  push:
    branches:
      - master
    tags:
      - release/*
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: prepare
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt autoremove -y
        sudo apt update -y --fix-missing
    - name: install
      run: >
        sudo apt install
        ninja-build
        libsdl2-dev
        libfmt-dev
        libepoxy-dev
        libglm-dev
        libphysfs-dev
    - name: configure
      run: |
        cmake --version
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: |
        cd build
        cmake --build . --target all
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: MyHumanoid-linux
        path: build
  build-windows:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: install
      shell: bash
      run: >
        vcpkg install
        libepoxy:x64-windows
        sdl3:x64-windows
        physfs:x64-windows
    - name: configure
      shell: bash
      run: >
        cmake --version ;
        cmake
        -S .
        -B build
        -G "Visual Studio 17 2022"
        -A x64
        -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        -D CMAKE_BUILD_TYPE=Release
        -D MH_USE_SYSTEM_FMT=OFF
        -D MH_USE_SYSTEM_GLM=OFF
        -D MH_USE_SYSTEM_PHYSFS=ON
        -D MH_USE_SYSTEM_SDL=ON
    - name: build
      shell: bash
      run: |
        cd build
        cmake --build . --target ALL_BUILD --config Release
        ls
        ls Release
    - name: package
      shell: bash
      run: |
        mkdir build-package
        cp build/Release/* build-package/
        cp build/MyHumanoid.data build-package/
        ls build-package
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: MyHumanoid-windows
        path: build-package
